### PR TITLE
fix(prefer-find-by): fix report with querySelector

### LINKED ISSUE #501: `prefer-find-by` reports `querySelector`
### Plugin version

4.12.4

### ESLint version

7.24.0

### Node.js version

14.16.0

### npm/yarn version

6.14.11

### Operating system

macOS Big Sur

### Bug description

I expect this code snippet NOT to be reported. Furthermore, error message and auto-fix have `undefined` instead of a meaningful message/fix.

```
    it('renders', async () => {
      const { container } = render(<App />)

      await waitFor(() =>
        expect(container.querySelector("[data-icon-name='bookmark-filled']")).toBeInTheDocument(), // reported
      )
    })
```

Auto-fixed to: `await container.findByundefined("[data-icon-name='bookmark-filled']")`

### Steps to reproduce

1. Setup `eslint-plugin-testing-library` 4.12.4
2. Enable `prefer-find-by` rule
3. Create a test with the above code snippet
4. Run eslint with `--fix`

### Error output/screenshots

```
error  Prefer `findByundefined` query over using `waitFor` + `querySelector`  testing-library/prefer-find-by
```

### ESLint configuration

```
    {
      files: ['*.test.ts', '*.test.tsx'],
      parser: '@typescript-eslint/parser',
      plugins: ['testing-library'],
      rules: {
        '@typescript-eslint/no-var-requires': 'off',
        'testing-library/prefer-find-by': 'error',
      },
    },
```

### Rule(s) affected

`prefer-find-by`

### Anything else?

_No response_

### Do you want to submit a pull request to fix this bug?

No

### PR DESCRIPTION
**Pull request by bpinto**
## Checks

- [x] I have read the [contributing guidelines](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/CONTRIBUTING.md).
- [ ] If some rule is added/updated/removed, I've regenerated the rules list.
- [ ] If some rule meta info is changed, I've regenerated the plugin shared configs.

## Changes

- No longer report invalid usages with a missing query method.
- Add a test covering the code changes.

## Context

Fixes #501

### CODE REVIEW

**Comment by bpinto** [comment]
It's my first contribution to the project so if my fix is bad/wrong let me know how I can improve this.

File: lib/rules/prefer-find-by.ts [hunk 1]
```diff
@@ -373,6 +373,10 @@ export default createTestingLibraryRule<Options, MessageIds>({
           const callArguments = getQueryArguments(argument.body);
           const queryMethod = fullQueryMethod.split('By')[1];
 
+          if (!queryMethod) {
+            return;
```
Comment (Belco90) [inline lib/rules/prefer-find-by.ts:377]: This partially fixes the issue. This `return` is wrapped within `isScreenSyncQuery` condition, so it will be only applied to `screen.foo` scenarios.

You need to do the same check + `return` a few lines below here, where the other `fullQueryMethod.split('By')[1]` is located.

File: tests/lib/rules/prefer-find-by.test.ts [hunk 2]
```diff
@@ -149,6 +149,14 @@ ruleTester.run(RULE_NAME, rule, {
         })
       `,
     },
+    {
+      code: `
+        import {screen, waitFor} from '@testing-library/foo';
+        it('tests', async () => {
+          await waitFor(() => expect(screen.querySelector('baz')).toBeInTheDocument());
```
Comment (Belco90) [inline tests/lib/rules/prefer-find-by.test.ts:156]: If you check the original issue #501, the problematic code was a bit different:

```js
    it('renders', async () => {
      const { container } = render(<App />)

      await waitFor(() =>
        expect(container.querySelector("[data-icon-name='bookmark-filled']")).toBeInTheDocument(), // reported
      )
    })
```

Can you add a test for this one too, please?

**Review by Belco90 — CHANGES_REQUESTED** [review]
Hi @bpinto! Thanks for your first contribution. The fix itself seems fine but handles the original issue partially. I've pointed out somewhere else where you need to apply the fix.

File: lib/rules/prefer-find-by.ts (hunk 1 above)
Comment (bpinto) [reply lib/rules/prefer-find-by.ts:377]: Thanks for catching that! I missed that this would not work for `container` queries.

File: tests/lib/rules/prefer-find-by.test.ts (hunk 2 above)
Comment (bpinto) [reply tests/lib/rules/prefer-find-by.test.ts:156]: I'll add this test, I missed that the original issue was slightly different to what I was experiencing on my side. :+1:

File: lib/rules/prefer-find-by.ts (hunk 1 above)
Comment (bpinto) [reply lib/rules/prefer-find-by.ts:377]: Hmm actually, I've added the test however it is not failing. `isScreenSyncQuery` is returning true.

```js
function isScreenSyncQuery(node: TSESTree.ArrowFunctionExpression) {
...
  return (
    helpers.isSyncQuery(node.body.callee.property) ||
    isWrappedInPresenceAssert || // this is evaluating to true
    isWrappedInNegatedPresenceAssert
  );
}

Comment (Belco90) [reply lib/rules/prefer-find-by.ts:377]: Ooh, you are right! My bad, sorry: I assumed the isScreenSyncQuery was coming from our helpers, but it's a function from the rule itself. This is fine then!

**Review by Belco90 — APPROVED** [review]
All good now, thank you very much!

**Comment by Belco90** [comment]
@all-contributors please add @bpinto for code and test.
