### PR TITLE
fix(no-wait-for-side-effects): detect await expressions

### LINKED ISSUE #742: Failure to detect `no-wait-for-side-effects` when used in conjunction with `await`
### Have you read the Troubleshooting section?

Yes

### Plugin version

v5.10.2

### ESLint version

v8.13.0

### Node.js version

18.13.0

### package manager and version

npm 8.19.3

### Operating system

Windows Version 10.0.19044 Build 19044

### Bug description

When writing Vue tests, I get no warning when I use side effects within with waitFor call-back **if** I await them. 

### Steps to reproduce

```ts
// Component.spec.tsx
import { screen, fireEvent, waitFor } from "@testing-library/vue";

it("some test", async () => {
  await waitFor(async () => {
    // I expect the warning 'Avoid using side effects within `waitFor` callback'
    await fireEvent.click(screen.getByTestId("something"));
  });
});
```

### Error output/screenshots

_No response_

### ESLint configuration

```cjs
/* eslint-env node */
require("@rushstack/eslint-patch/modern-module-resolution");

module.exports = {
  root: true,
  plugins: ["vitest"],
  extends: [
    "plugin:vue/vue3-essential",
    "eslint:recommended",
    "plugin:jest-formatting/recommended",
    "@vue/eslint-config-typescript/recommended",
    "@vue/eslint-config-prettier",
    "plugin:testing-library/vue",
  ],
  env: {
    "vue/setup-compiler-macros": false,
  },
  rules: {
    eqeqeq: ["warn", "always"],
    "vitest/no-conditional-tests": "warn",
    "vitest/no-focused-tests": "warn",
    "vitest/no-identical-title": "warn",
    "vitest/no-skipped-tests": "warn",
    "require-await": "warn",
  },
  overrides: [
    {
      files: ["cypress/integration/**.spec.{js,ts,jsx,tsx}"],
      extends: ["plugin:cypress/recommended"],
    },
  ],
};
```

### Rule(s) affected

<a href="https://github.com/testing-library/eslint-plugin-testing-library/tree/main/docs/rules/no-wait-for-side-effects.md" target="_blank">no-wait-for-side-effects</a>

### Anything else?

_No response_

### Do you want to submit a pull request to fix this bug?

No

### PR DESCRIPTION
**Pull request by StyleShit**
Closes #742

### CODE REVIEW

File: lib/node-utils/index.ts [hunk 1]
```diff
@@ -374,6 +374,10 @@ export function getPropertyIdentifierNode(
 		return getPropertyIdentifierNode(node.expression);
 	}
 
+	if (ASTUtils.isAwaitExpression(node)) {
+		return getPropertyIdentifierNode(node.argument);
+	}
```
Comment (StyleShit) [inline lib/node-utils/index.ts:379]: `getPropertyIdentifierNode` stopped its recursive iteration when it encountered an await expression, and therefore returned `false`

Comment (Belco90) [reply lib/node-utils/index.ts:379]: praise: Good catch!

File: tests/lib/rules/no-wait-for-side-effects.test.ts [hunk 2]
```diff
@@ -797,5 +807,19 @@ ruleTester.run(RULE_NAME, rule, {
 				],
 			} as const,
 		]),
+
+		...SUPPORTED_TESTING_FRAMEWORKS.flatMap((testingFramework) => [
```
Comment (Belco90) [inline tests/lib/rules/no-wait-for-side-effects.test.ts:811]: suggestion (blocking): Please add a test for the scenario reported in #742 description.

**Review by Belco90 — CHANGES_REQUESTED** [review]
Thanks for addressing this bug!

I see code coverage went down, so Codecov complains. Can you add extra tests for `no-wait-for-multiple-assertions`? It's indirectly affected ([see more details](https://app.codecov.io/gh/testing-library/eslint-plugin-testing-library/pull/1008/indirect-changes)).

File: tests/lib/rules/no-wait-for-side-effects.test.ts (hunk 2 above)
Comment (StyleShit) [reply tests/lib/rules/no-wait-for-side-effects.test.ts:811]: Done

**Comment by StyleShit** [comment]
> Thanks for addressing this bug!
> 
> I see code coverage went down, so Codecov complains. Can you add extra tests for `no-wait-for-multiple-assertions`? It's indirectly affected ([see more details](https://app.codecov.io/gh/testing-library/eslint-plugin-testing-library/pull/1008/indirect-changes)).

there was a redundant `isExpressionStatement` check in the code

**Comment by Belco90** [comment]
> On a side note - the CI is so fast, I like it! 🚀

I'm glad you like the CI speed! We can do even better, hopefully we can switch to vitest soon.
