### PR TITLE
fix(prefer-user-event): format list of userEvent methods correctly 

### LINKED ISSUE #310: [v4][prefer-user-event] malformed error message for `fireEvent.keyDown`
We have code that (minimized for repro) looks like:

```js
await fireEvent.keyDown(thing);
```

That produces an error: `Prefer using  or userEvent.tab() over fireEvent.keyDown()`. Seems like the first alternative suggestion is missing (note the double-space).

This is with `4.0.0-beta.3`

### PR DESCRIPTION
**Pull request by Belco90**
Closes #310

### CODE REVIEW

File: lib/rules/prefer-user-event.ts [hunk 1]
```diff
@@ -49,17 +49,14 @@ export const MappingToUserEvent: Record<string, UserEventMethodsType[]> = {
...
-    (method: string) => `userEvent.${method}()`
+  const userEventMethods = MAPPING_TO_USER_EVENT[fireEventMethod].map(
+    (methodName) => `userEvent.${methodName}`
   );
-  const { length } = allMethods;
 
-  const init = length > 2 ? allMethods.slice(0, length - 2).join(', ') : '';
-  const last = `${length > 1 ? ' or ' : ''}${allMethods[length - 1]}`;
-  return `${init}${last}`;
+  return userEventMethods.join(', ').replace(/, ([a-zA-Z.]+)$/, ', or $1');
```
Comment (Belco90) [inline lib/rules/prefer-user-event.ts:56]: I'd like to just use `Intl.ListFormat` here, but it's available from node v13 so we can't stick to it until we drop node v10 and node v12 compatibility 😅

File: tests/lib/rules/prefer-user-event.test.ts [hunk 2]
```diff
@@ -28,6 +28,26 @@ function createScenarioWithImport<
 
 const ruleTester = createRuleTester();
 
+function formatUserEventMethodsMessage(fireEventMethod: string): string {
```
Comment (Belco90) [inline tests/lib/rules/prefer-user-event.test.ts:31]: I reimplemented here the same method so I don't use the very same implementation. Otherwise, it would be tricky to catch errors formatting the message.

File: tests/lib/rules/prefer-user-event.test.ts [hunk 3]
```diff
@@ -295,10 +320,21 @@ ruleTester.run(RULE_NAME, rule, {
           endColumn: 22,
           data: {
             userEventMethods:
-              'userEvent.click(), userEvent.type() or userEvent.deselectOptions()',
+              'userEvent.click, userEvent.type, userEvent.selectOptions, or userEvent.deselectOptions',
```
Comment (Belco90) [inline tests/lib/rules/prefer-user-event.test.ts:323]: @epmatsw nice catch opening this issue! This test should have caught that, but has the wrong expected output :(
